### ISSUE TITLE
Bug when running similarity.py

### ISSUE THREAD

**Issue by gjkapral** [wouterboomsma/encore#2]
I was trying to run the example files, but when I try any of the shellscripts in examples directory, it always gave the same error. Same thing if I tried to run similarity.py without the script. Here is the traceback:

2016-08-08,16:54:35.204 : Loading ensembles . . .
Traceback (most recent call last):
  File "similarity.py", line 851, in <module>
    frame_interval = frame_interval ) )
  File "/home/hlab4/.local/lib/python2.7/site-packages/ENCORE-0.7-py2.7-linux-x86_64.egg/encore/Ensemble.py", line 127, in **init**
    self.coordinates = self.get_coordinates(subset_selection_string = self.atom_selection_string)
  File "/home/hlab4/.local/lib/python2.7/site-packages/ENCORE-0.7-py2.7-linux-x86_64.egg/encore/Ensemble.py", line 189, in get_coordinates
    subset_coordinates[k] = subset_selection.coordinates(time_step)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/utils.py", line 96, in newfunc
    return func(_args, *_kwds)
TypeError: coordinates() takes exactly 1 argument (2 given)

If this isn't actually a bug, then any advice on why it isn't working would be appreciated. I have tried this on both local and global installs just in case that was a factor, and I got the same error each time.

**Comment by mtiberti** [comment]
Hi,
which version of MDAnalysis are you using as a dependency for ENCORE? MDAnalysis is still in active development and changing at fast pace, and we were unable to keep up with all the changes that broke backwards compatibility with ENCORE in the most recent versions. In order to mitigate this effect we are currently in the process of merging ENCORE with the MDAnalysis package itself, a process which is not completed yet ( https://github.com/MDAnalysis/mdanalysis/pull/797 ) even though we're likely close. I would suggest to start from this version, as it's the most current and also includes fixes for bugs that we identified during the merging process. Once this is completed this repository will likely be deprecated and only the version included in MDAnlaysis will be actively developed.
